### ISSUE TITLE
点播配置数据中的spider项应当是可选的

### ISSUE THREAD

**Issue by karma-sun** [Greatwallcorner/TV-Multiplatform#12]
点播配置数据中的spider项应当是可选的,现在使用如下所示配置并不需要任何spider但会因为缺spider项报错“配置数据为空”
{
    "sites": [{
        "key": "xxx",
        "name": "xxx",
        "type": 1,
        "api": "http://127.0.0.1:8080",
        "searchable": 1,
        "quickSearch": 1,
        "filterable": 0
    }]
}

**Comment by Greatwallcorner** [comment]
我看看吧

**Comment by Greatwallcorner** [comment]
你试试
