### ISSUE TITLE
资源切换现在版本会不定时报错导致关闭程序

### ISSUE THREAD

**Issue by simple1zombie** [Greatwallcorner/TV-Multiplatform#2]
发现了一点问题，搜索出资源之后点击切换左侧资源链接之后时不时会出现这种报错，大佬看看能不能修复一下
![微信图片_20240429131159](https://github.com/Greatwallcorner/TV-Multiplatform/assets/168398411/f6c48ab5-ab82-4d05-9b2c-7e0c88b1363e)
![微信图片_20240429131216](https://github.com/Greatwallcorner/TV-Multiplatform/assets/168398411/dcd5242e-fe24-4a31-94f6-fbfa7d83b6ef)

**Comment by Greatwallcorner** [comment]
左侧什么资源链接 不太清楚 可以录个视频
