### ISSUE TITLE
能内置下播放器不.或者播放器支持手头选择. 而不是自己填写地址.. 我自己填写了好几个 都不成功

### ISSUE THREAD

**Issue by Xiaocge** [Greatwallcorner/TV-Multiplatform#5]

**Comment by lushunming** [comment]
![image](https://github.com/Greatwallcorner/TV-Multiplatform/assets/10239731/20794bea-ce15-491d-8702-6188f14977c6)
这样填

**Comment by Greatwallcorner** [comment]
你是mac吗
