### ISSUE TITLE
win11点exe点不动，打不开

### ISSUE THREAD

**Issue by nlxxtw** [Greatwallcorner/TV-Multiplatform#9]
![image](https://github.com/Greatwallcorner/TV-Multiplatform/assets/49474003/fe13d5fb-1098-412d-8776-63497bb94672)

**Comment by nlxxtw** [comment]
最新版可以打开了，但是
![image](https://github.com/Greatwallcorner/TV-Multiplatform/assets/49474003/a41ac348-a250-435f-aaff-47bae18075f3)
变成这样了

**Comment by Greatwallcorner** [comment]
群里说话
